"""
generate_examples_readme.py

Reads all Python scripts in the examples/ directory, extracts their docstrings
and any expected output (from a comment block or running the script), and
generates a README.md for the examples subfolder.

Usage:
    uv run scripts/generate_examples_readme.py

Run from the project root directory.
"""

import ast
import re
import subprocess
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).parent.parent
EXAMPLES_DIR = PROJECT_ROOT / "examples"
README_PATH = EXAMPLES_DIR / "README.md"
TIMEOUT = 60  # seconds per script

# Order in which groups appear in the README
GROUP_ORDER = [
    "Single Step AC",
    "Single Step DC",
    "Multi Step AC",
    "Multi Step DC",
    "Storage AC",
    "Storage DC",
    "Sparse vs Dense AC",
    "Other",
]

# Patterns matched against filename (lowercase). First match wins.
GROUP_PATTERNS = [
    (r"storage.*ac|ac.*storage",   "Storage AC"),
    (r"storage.*dc|dc.*storage",   "Storage DC"),
    (r"sparse.*ac|ac.*sparse",     "Sparse vs Dense AC"),
    (r"multistep.*ac|ac.*multistep|multistep(?!.*dc)", "Multi Step AC"),
    (r"multistep.*dc|dc.*multistep","Multi Step DC"),
    (r"ac_vs_dc|lossy_dc|single_step.*dc|dc.*single_step", "Single Step DC"),
    (r"single_step|ac",            "Single Step AC"),
]

# Extract case size (number after "case") for sorting within a group
CASE_SIZE_RE = re.compile(r"case(\d+)")


def classify_script(filepath: Path) -> str:
    """Assign a script to a group based on its filename."""
    name = filepath.stem.lower()
    for pattern, group in GROUP_PATTERNS:
        if re.search(pattern, name):
            return group
    return "Other"


def case_size(filepath: Path) -> int:
    """Return the numeric case size for sorting, or 0 if not found."""
    match = CASE_SIZE_RE.search(filepath.stem)
    return int(match.group(1)) if match else 0


def extract_docstring(filepath: Path) -> str:
    """Extract the module-level docstring from a Python file."""
    try:
        source = filepath.read_text(encoding="utf-8")
        tree = ast.parse(source)
        docstring = ast.get_docstring(tree)
        return docstring or "_No description provided._"
    except SyntaxError:
        return "_Could not parse file._"


def run_script(filepath: Path) -> str:
    """Run a script and capture its stdout output."""
    try:
        result = subprocess.run(
            [sys.executable, str(filepath)],
            capture_output=True,
            text=True,
            timeout=TIMEOUT,
            cwd=PROJECT_ROOT,
        )
        output = result.stdout.strip()
        if result.returncode != 0:
            error = result.stderr.strip()
            return f"_Script exited with errors:_\n```\n{error}\n```"
        return output if output else "_No output._"
    except subprocess.TimeoutExpired:
        return f"_Script timed out after {TIMEOUT} seconds._"
    except Exception as e:
        return f"_Could not run script: {e}_"


def slugify(text: str) -> str:
    """Convert a heading string to a GitHub-flavoured markdown anchor slug."""
    text = text.lower()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[\s]+", "-", text.strip())
    return text


def script_anchor(name: str) -> str:
    """Return the anchor GitHub will generate for a ## `filename.py` heading."""
    return slugify(name)


def generate_readme(examples_dir: Path, readme_path: Path) -> None:
    scripts = sorted(examples_dir.glob("*.py"))
    scripts = [s for s in scripts if s.name != "__init__.py"]

    if not scripts:
        print("No example scripts found.")
        return

    # --- Group and sort scripts ---
    groups: dict[str, list[Path]] = {g: [] for g in GROUP_ORDER}
    for script in scripts:
        group = classify_script(script)
        groups.setdefault(group, []).append(script)

    for group in groups:
        groups[group].sort(key=case_size)

    # --- Collect output up front so we can build TOC ---
    # structure: [(group, [(script, docstring, output), ...]), ...]
    sections: list[tuple[str, list[tuple[Path, str, str]]]] = []
    for group in GROUP_ORDER:
        if not groups.get(group):
            continue
        entries = []
        for script in groups[group]:
            print(f"Processing {script.name}  [{group}]")
            docstring = extract_docstring(script)
            output = run_script(script)
            entries.append((script, docstring, output))
        sections.append((group, entries))

    # --- Build markdown ---
    lines = [
        "# Examples",
        "",
        "This folder contains example scripts demonstrating various features of the project.",
        "This file is auto-generated by `scripts/generate_examples_readme.py`. Do not edit manually.",
        "",
        "---",
        "",
        "## Table of Contents",
        "",
    ]

    # TOC entries
    for group, entries in sections:
        group_slug = slugify(group)
        lines.append(f"- [{group}](#{group_slug})")
        for script, _, _ in entries:
            anchor = script_anchor(script.name)
            lines.append(f"  - [`{script.name}`](#{anchor})")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Section bodies
    for group, entries in sections:
        lines.append(f"## {group}")
        lines.append("")
        for script, docstring, output in entries:
            lines.append(f"### `{script.name}`")
            lines.append("")
            lines.append(docstring)
            lines.append("")
            lines.append("#### Expected Output")
            lines.append("")
            lines.append("```")
            lines.append(output)
            lines.append("```")
            lines.append("")
        lines.append("---")
        lines.append("")

    readme_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nREADME written to {readme_path}")


if __name__ == "__main__":
    generate_readme(EXAMPLES_DIR, README_PATH)